version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run sample solution
          command: |
            . venv/bin/activate
            echo "8" | python3 make_sat.py
