name: Python application

on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.5"
    - name: Install dependencies
      run: |
        sudo apt-get install minisat
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v